import Main from '~/layouts/main';

import IndividualCourse from '../../components/IndividualCourse';
import data from '../../mock/individual.json';

export default function Individual({ posts }) {
  return (
    <Main>
      <div className='px-8-mt-10 '>
        <head>
          <title>Article Preview Component</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <link
            rel='stylesheet'
            href='https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css'></link>
          <script src='https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js'></script>
        </head>
        <header className='relative flex items-center justify-center h-96 mb-12 overflow-hidden '>
          <img
            className='absolute z-10 w-auto min-w-full min-h-full max-w-none '
            src='/images/tile.jpeg'
          />
        </header>

        <div className='flex justify-center lg:grid-cols-4 md:grid-cols-3 gap-3 sm:grid-cols-2 '>
          {posts.map((post) => {
            return <IndividualCourse post={post} key={post.id} />;
          })}
        </div>
      </div>
    </Main>
  );
}

export async function getStaticProps() {
  return {
    props: {
      posts: data,
    },
  };
}
